/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rmconyhxvmwfudrwwfiv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtY29ueWh4dm13ZnVkcnd3Zml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MTk1ODIsImV4cCI6MjA3NzA5NTU4Mn0.UmeHT_5x-1_hPPbvVF85MkIAPhr-SWcBBeCNKf2FA8g"